<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>

        let p = new Promise((reslove,reject)=>{
            reject('失败了')
        })
        // p.then((res)=>{
        //     console.log(res);
        // },(err)=>{
        //     console.log(err);
        // })

        // 捕获promise错误 当状态变为失败状态时 则会自动调用catch方法。
        p.catch((err)=>{
            console.log(err);
        })
        // 注意若catch和then方法一块儿使用时 ，会优先执行 then方法中失败回调，若then方法中没有定义失败回调则才会调用catch方法
        p.then(()=>{
            console.log('成功了');
        }).catch(()=>{
            console.log('失败了22222222222222222');
        })


        let p1 = new Promise((reslove,reject)=>{
            // reslove('成功了')
            reject('失败了')
        })
        // 无论状态失败或成功都会调用finally方法
        p1.finally(()=>{
            console.log('无论状态失败或成功都会调用finally方法');
        }).catch(()=>{
            console.log('失败了');
        })
    </script>
</body>
</html>